### ISSUE TITLE
Accessibility issue in the standalone Foundry VTT application

### ISSUE THREAD

**Issue by Ronnie-McDurgen** [itamarcu/ZoomPanOptions#24]
I hope I am not being rude by posting this here. I asked around in the Official Foundry Discord, and they heartily encouraged me to try posting it here, and assured me that it would not be rude of me to do so. Here goes:

I'm having a problem that is preventing me from switching my campaign over to Foundry :-/ 

The thing is, I'm disabled, in such a way that I cannot use a regular mouse. Instead, I use a Logitech T650 touchpad, which rests on a thin plank of wood in my lap. And, on roll20, I use two fingers to pan up/down and left/right, as well as to zoom whenever I hold down a keyboard button and move the two fingers up/down. This gives an extremely smooth panning and zooming experience in roll20, but I have been unable to get that functionality to work in Foundry.

I tried using your Zoom/Pan Options module to see if that would fix the issue, but no luck. Here are the issues that I found: 

1) The vertical scrolling works to pan up/down, but it is very "choppy". That is to say, it jumps many pixels at a time, rather than being "smooth". This happened even when I toned the sensitivity down so low that I would never have been able to use Foundry that way. And, even with the sensitivity toned down that low, the jumpiness of the scrolling gave me nausia.

2) The horizontal scrolling to pan left/right has an odd behavior going on right now. Whenever I test it, I can do a single scroll, either left or right, and then after that, it is completely stuck, that is to say it is unable to scroll in either direction. But if I do a single scroll up or down, then that seems to "reset" this bug. That is to say, after doing a single scroll up or down, then I am once again able to do one (and only one) scroll in either the left or the right direction.

3) The horizontal scrolling seems to move about 50 times faster than the vertical scrolling. I tested this at multiple sensitivity settings, and that seemed to be the ratio each time. And also, it was "choppy" in the same way that the vertical scrolling was.

Thanks for reading this. I hope it wasn't rude, and I hope that I'll one day be able to move my campaign over to Foundry VTT :-)

**Comment by itamarcu** [comment]
hi Ronnie!  I'm glad to hear your feedback, it's definitely not rude and you're more than welcome to contact me here or through discord (I'm `shem#0226`).

I have some basic questions:

- you say "Standalone Foundry VTT application".  have you tried using the touchpad through browsers?  Chrome and Firefox both behave a bit differently with this mod (that's why I added the sensitivity setting), so it's possible that the standalone app has yet another different behavior.
- I haven't been able to reproduce the bug you're describing, though I have different equipment:  I have a keyboard+mouse computer running with Chrome (works, and also works with the standalone app), and a MacBook Pro where I use the touchpad  (seems to work well enough, too).  So, I'm guessing the bug is related either to the standalone app or to your specific Logitech T650 touchpad.

If trying in a browser doesn't help you - could you send me a direct message on Discord?  I could try changing some code for you to see if your touchpad behaves differently and to see how I can work around it.

**Comment by itamarcu** [comment]
Closing this issue, please reopen if there is no information.
